// react_animation/src/components/Squares.js
import React, { useEffect, useRef, useState } from 'react';
import './Squares.css';

const Square = ({ left }) => {
    const ref = useRef();
    const direction = useRef(1); // 1 = down, -1 = up
    const topRef = useRef(Math.random() * (window.innerHeight)); // initial random top

    useEffect(() => {
        const el = ref.current;
        const squareHeight = el.offsetHeight;
        const maxTop = window.innerHeight - squareHeight;
        let top = topRef.current;

        const animate = () => {
            top += direction.current;

            // Reverse direction if hitting top or bottom
            if (top >= maxTop) {
                top = maxTop;
                direction.current = -1;
            } else if (top <= 0) {
                top = 0;
                direction.current = 1;
            }

            el.style.top = `${top}px`;
            requestAnimationFrame(animate);
        };

        // Initial placement
        el.style.left = `${left}%`;
        el.style.top = `${top}px`;

        animate();
    }, [left]);

    return <div ref={ref} className="square" />;
};

const Squares = () => {
    const [squareCount, setSquareCount] = useState(10);

    const add10 = () => setSquareCount(prev => prev + 10);
    const resetSquares = () => setSquareCount(10);

    return (
        <div className="container">
            <div className="sidebar">
                <p>Top and left changes</p>
                <button onClick={add10} className="btn">Add 10 Squares</button>
                <button onClick={resetSquares} className="btn">Reset Squares</button>
            </div>
            <div className="square-area">
                {Array.from({ length: squareCount }).map((_, index) => {
                    const laneCount = 20;
                    const column = index % laneCount;
                    const left = (column / laneCount) * 100;
                    return <Square key={index} left={left} />;
                })}
            </div>
        </div>
    );
};

export default Squares;

// angular_animation/src/app/squares/squares.component.ts
// squares.component.ts
import {
  Component,
  Input,
  ViewChild,
  ElementRef,
  AfterViewInit,
  OnInit,
  signal,
  computed
} from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-square',
  standalone: true,
  imports: [CommonModule],
  template: '<div #squareRef class="square"></div>',
  styleUrls: ['./squares.component.css']
})
export class SquareComponent implements AfterViewInit {
  @Input() left!: number;
  @ViewChild('squareRef') squareRef!: ElementRef<HTMLDivElement>;

  private direction = 1;
  private y = Math.random() * (window.innerHeight - 20);

  ngAfterViewInit(): void {
    const el = this.squareRef.nativeElement;
    const squareHeight = 20;
    const maxY = window.innerHeight - squareHeight;
    const x = (this.left / 100) * window.innerWidth;

    const animate = () => {
      this.y += this.direction;

      if (this.y >= maxY) {
        this.y = maxY;
        this.direction = -1;
      } else if (this.y <= 0) {
        this.y = 0;
        this.direction = 1;
      }

      el.style.transform = `translate(${x}px, ${this.y}px)`;
      requestAnimationFrame(animate);
    };

    animate();
  }
}

@Component({
  selector: 'app-squares',
  standalone: true,
  imports: [CommonModule, SquareComponent],
  templateUrl: './squares.component.html',
  styleUrls: ['./squares.component.css']
})
export class SquaresComponent implements OnInit {
  squareCount = signal(10);

  squares = computed(() => Array.from({ length: this.squareCount() }, (_, i) => i));

  ngOnInit(): void {
    // Optional: could be used to debug re-renders
  }

  add10(): void {
    this.squareCount.update(c => c + 10);
  }

  resetSquares(): void {
    this.squareCount.set(10);
  }
}

<!-- squares.component.html -->
<div class="container">
  <div class="sidebar">
    <p>Transform changes</p>
    <button (click)="add10()" class="btn">Add 10 Squares</button>
    <button (click)="resetSquares()" class="btn">Reset Squares</button>
  </div>
  <div class="square-area">
    <app-square
      *ngFor="let i of squares()"
      [left]="(i % 20) * 5"
    ></app-square>
  </div>
</div>
